services:
  fossflow:
    image: stnsmith/fossflow:latest
    pull_policy: always
    container_name: fossflow
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ENABLE_SERVER_STORAGE=${ENABLE_SERVER_STORAGE:-true}
      - STORAGE_PATH=/data/diagrams
      - ENABLE_GIT_BACKUP=${ENABLE_GIT_BACKUP:-false}
      - HTTP_AUTH_USER=${HTTP_AUTH_USER:-}
      - HTTP_AUTH_PASSWORD=${HTTP_AUTH_PASSWORD:-}
    volumes:
      - ./diagrams:/data/diagrams
    networks:
      - devops-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`fossflow.dhlabs.cl`)"
      - "traefik.http.routers.portfolio.service=fossflow"
      - "traefik.http.routers.portfolio.entrypoints=web"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
networks:
  devops-network:
    external: true
