name: Deploy_ando-server

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #hola
      - name: build
        run: |
              docker compose build --no-cache 
              sleep 3
              docker compose up -d 
      - name: healthcheck container
        run: |
          sleep 6
          docker ps | grep foss
          docker logs foss
